### ISSUE TITLE
Tarball large

### ISSUE THREAD

**Issue by phavekes** [OpenConext/Stepup-SelfService#207]
The tarball of this component is ~60MB in size, where other components are only 5-7MB. Probably to much is added to the archive.

**Comment by tvdijen** [comment]
The culprit is mpdf which was added between 2.7.2 and 2.8.0

**Comment by tvdijen** [comment]
Perhaps this is a good alternative for mpdf:  https://github.com/dompdf/dompdf

**Comment by tvdijen** [comment]
Not to me
