### ISSUE TITLE
4.0: Feature request: completely disable SMS recovery tokens

### ISSUE THREAD

**Issue by tvdijen** [OpenConext/Stepup-SelfService#271]
I'm not able to work with either Spryng or Messagebird, so I would like to be able to disable SMS recovery tokens completely. A feature toggle would be very helpful!

**Comment by MKodde** [comment]
It makes sense to allow disabling one of the recovery token types. Not using SMS for one is a very legitimate reason for you require it to be disabled. This never crossed our minds while building this feature.

I opened #274 addressing this issue.

**Comment by tvdijen** [comment]
Was closed in #274
